version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\SolutionInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-pre'
before_build:
- cmd: nuget restore legacy\Basics.sln
build:
  project: legacy\Basics.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: JU30GUQSjsq71xr+fc3Ps0bYxFmsmrNJnpvAmRE8Tgrbj1tHICONHsnvoq91VYML